services:
  frontend:
    build: ./frontend
    ports:
    - "5173:5173"
    environment:
      - VITE_API_URL=https://friendly-palm-tree-5w4v9jp4jwqh4prv-3000.app.github.dev
    depends_on:
      - backend


  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pdfgen
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src  # hot reload en dev

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db    # persistance entre restarts

volumes:
  mongo_data:


